env:
  dev:
    experiment: "/Shared/dbx/dbx_demand_forecast/dev_dbx_demand_forecast"
    input:
      path: "gs://dbx-demand-forecast/dev/input"
      database: "dev"
      table: "input"
    output:
      path: "gs://dbx-demand-forecast/dev/split"
      database: "dev"
      table: "split"
    test_size: 90
  prod:
    experiment: "/Shared/dbx/dbx_demand_forecast/prod_dbx_demand_forecast"
    input:
      path: "gs://dbx-demand-forecast/prod/input"
      database: "prod"
      table: "input"
    output:
      path: "gs://dbx-demand-forecast/prod/split"
      database: "prod"
      table: "split"
    test_size: 90
