# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "11.3.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "n1-standard-4"

build:
  python: "poetry"

environments:
  dev:
    workflows:
    - name: "dev-dbx-demand-forecast"
      job_clusters:
        - job_cluster_key: "dev"
          <<: *basic-static-cluster
      tasks:
        - task_key: "ingest"
          job_cluster_key: "dev"
          python_wheel_task:
              package_name: "dbx_demand_forecast"
              entry_point: "ingest"
              parameters:
              - "--conf-file"
              - "file:fuse://conf/tasks/ingest_config.yml"
              - "--env"
              - "dev"
  prod:
    workflows:
    - name: "prod-dbx-demand-forecast"
      job_clusters:
        - job_cluster_key: "prod"
          <<: *basic-static-cluster
      tasks:
        - task_key: "ingest"
          job_cluster_key: "prod"
          python_wheel_task:
              package_name: "dbx_demand_forecast"
              entry_point: "ingest"
              parameters:
              - "--conf-file"
              - "file:fuse://conf/tasks/ingest_config.yml"
              - "--env"
              - "prod"
